In [6]:
import pandas as pd

In [ ]:
DATA_PATH = '/home/MohammadNabulsi/Essay Evaluator/data/openreview/iclr2024_openreview_7000.json'
DATA_PATH = '/home/MohammadNabulsi/Essay Evaluator/data/openreview/testing/openreview_10000_merged_2024orig_plus_2025.json'
# DATA_PATH = '/home/MohammadNabulsi/Essay Evaluator/dist/accepted/openreview_non_rejected_until_10k.json'

In [59]:
df = pd.read_json(DATA_PATH)

In [60]:
df.head()

,paper_id,number,title,abstract,keywords,pdf,n_reviews,reviews,decision,decision_comment,source_venue,accepted_by,is_non_rejected,submission_raw,replies_raw,decision_raw
0,zzo3Sy3NSX,4956,Your Language Model Secretly Contains Personal...,Humans shift between different personas depend...,"[Large Language Models, Persona Modeling]",/pdf/217ef31a5b92c8f2cf057c7601381cc6af8c901c.pdf,4,"[{'rating': 6, 'confidence': 3, 'summary': 'Th...",Accept (Poster),,ICLR.cc/2026/Conference,ICLR.cc/2026/Conference/Submission4956/-/Decision,True,"{'id': 'zzo3Sy3NSX', 'forum': 'zzo3Sy3NSX', 'c...",[{'content': {'title': {'value': 'Paper Decisi...,{'content': {'title': {'value': 'Paper Decisio...
1,zzTQISAGUp,23782,Polychromic Objectives for Reinforcement Learning,Reinforcement learning fine-tuning (RLFT) is a...,"[Reinforcement Learning, Exploration]",/pdf/c4ab101674ac9d724ef98dd20bcf410ba92ccbaa.pdf,4,"[{'rating': 6, 'confidence': 3, 'summary': 'Th...",Accept (Poster),,ICLR.cc/2026/Conference,ICLR.cc/2026/Conference/Submission23782/-/Deci...,True,"{'id': 'zzTQISAGUp', 'forum': 'zzTQISAGUp', 'c...",[{'content': {'title': {'value': 'Paper Decisi...,{'content': {'title': {'value': 'Paper Decisio...
2,zzTDulLys0,9335,vAttention: Verified Sparse Attention via Samp...,State-of-the-art sparse attention methods for ...,[sparse attention],/pdf/b353d1d314c97b316faf589c3fd73cec7d570b3a.pdf,4,"[{'rating': 6, 'confidence': 3, 'summary': 'Th...",Accept (Poster),,ICLR.cc/2026/Conference,ICLR.cc/2026/Conference/Submission9335/-/Decision,True,"{'id': 'zzTDulLys0', 'forum': 'zzTDulLys0', 'c...",[{'content': {'title': {'value': 'Paper Decisi...,{'content': {'title': {'value': 'Paper Decisio...
3,zyRmy0Ch9a,6981,Diffusion Bridge Variational Inference for Dee...,Deep Gaussian processes (DGPs) enable expressi...,"[Deep Gaussian Processes, Diffusion Bridge, Va...",/pdf/cca938ee8704d1a41017b87af92f690a6a013172.pdf,4,"[{'rating': 8, 'confidence': 3, 'summary': 'Th...",Accept (Poster),,ICLR.cc/2026/Conference,ICLR.cc/2026/Conference/Submission6981/-/Decision,True,"{'id': 'zyRmy0Ch9a', 'forum': 'zyRmy0Ch9a', 'c...",[{'content': {'title': {'value': 'Paper Decisi...,{'content': {'title': {'value': 'Paper Decisio...
4,zyLI9LEmry,10578,Preference-based Policy Optimization from Spar...,Offline reinforcement learning (RL) holds the ...,"[Reinforcement Learning, Offline Reinforcement...",/pdf/50b38bf4272c45bb70319c0d3d3b3fefd8a4ee09.pdf,4,"[{'rating': 4, 'confidence': 4, 'summary': 'Th...",Accept (Poster),,ICLR.cc/2026/Conference,ICLR.cc/2026/Conference/Submission10578/-/Deci...,True,"{'id': 'zyLI9LEmry', 'forum': 'zyLI9LEmry', 'c...",[{'content': {'title': {'value': 'Paper Decisi...,{'content': {'title': {'value': 'Paper Decisio...

In [61]:
df.columns

Index(['paper_id', 'number', 'title', 'abstract', 'keywords', 'pdf',
       'n_reviews', 'reviews', 'decision', 'decision_comment', 'source_venue',
       'accepted_by', 'is_non_rejected', 'submission_raw', 'replies_raw',
       'decision_raw'],
      dtype='str')

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   paper_id          10000 non-null  str
 1   number            10000 non-null  int64
 2   title             10000 non-null  str
 3   abstract          10000 non-null  str
 4   keywords          10000 non-null  object
 5   pdf               10000 non-null  str
 6   n_reviews         10000 non-null  int64
 7   reviews           10000 non-null  object
 8   decision          10000 non-null  str
 9   decision_comment  9996 non-null   str
 10  source_venue      10000 non-null  str
 11  accepted_by       10000 non-null  str
 12  is_non_rejected   10000 non-null  bool
 13  submission_raw    10000 non-null  object
 14  replies_raw       10000 non-null  object
 15  decision_raw      10000 non-null  object
dtypes: bool(1), int64(2), object(5), str(8)
memory usage: 16.6+ MB

In [63]:
sample = df.iloc[0, :]

In [64]:
sample['reviews'][0]['rating'][0]

TypeError: 'int' object is not subscriptable

In [65]:
df['n_reviews'].median()

np.float64(4.0)

In [50]:
df['n_reviews'].value_counts()

n_reviews
4    6432
3    2156
5    1072
0     169
6     132
2      15
7      15
8       7
1       1
9       1
Name: count, dtype: int64

In [51]:
# Drop rows where num_reviews == 0
# df = df[df["n_reviews"] != 0].copy()

In [52]:
df['n_reviews'].median(), df['n_reviews'].value_counts()

(np.float64(4.0),
 n_reviews
 4    6432
 3    2156
 5    1072
 0     169
 6     132
 2      15
 7      15
 8       7
 1       1
 9       1
 Name: count, dtype: int64)

In [53]:
first_reviews = df.iloc[0]["reviews"]

# convert reviews to strings for uniqueness check
unique_reviews = list(set(map(str, first_reviews)))

print(f"Total reviews: {len(first_reviews)}")
print(f"Unique reviews: {len(unique_reviews)}")

for i, review in enumerate(unique_reviews, 1):
    print(f"\n--- Unique Review {i} ---")
    print(review)

Total reviews: 4
Unique reviews: 4

--- Unique Review 1 ---
{'rating': '6: marginally above the acceptance threshold', 'confidence': '3: You are fairly confident in your assessment. It is possible that you did not understand some parts of the submission or that you are unfamiliar with some pieces of related work. Math/other details were not carefully checked.', 'summary': 'The study focuses on understanding the interactions between microorganisms, which is of significant importance in both medical and environmental contexts. The authors introduce a novel approach by modeling bacterial communities using graph neural networks (GNNs) directly from the genomes of the bacteria. The inherent properties of GNNs, such as permutation invariance, allow them to effectively capture the relationships within the bacterial set, thus offering combinatorial generalization.', 'strengths': '- Novel problem setup and the first use of GNN to tackle this problem. \n- The use of GNN matches with the data well since it is modeling a dynamic system. \n- Very interesting set of experiments and they are extensive. \n- The presentation is nice and clear.\n- Nice simulation data construction and results.', 'weaknesses': '- Methodological novelty is limited since it is basically fitting a GNN on a bacterial community graph. This is not to say the novelty of the paper is limited. Since I do believe it is tackling an interesting new problem with impact. I would suggest the authors consider a journal paper instead.'}

--- Unique Review 2 ---
{'rating': '3: reject, not good enough', 'confidence': '4: You are confident in your assessment, but not absolutely certain. It is unlikely, but not impossible, that you did not understand some parts of the submission or that you are unfamiliar with some pieces of related work.', 'summary': 'The paper aims at predicting steady-state composition of microbial communities from the gene content of their genomes using graph neural networks.', 'strengths': 'Understanding how distinct bacteria form communities is an important problem, and the manuscript provides a solid introduction to the topic and, in the experimental section, asks important questions about our ability to understand community formation.', 'weaknesses': 'The proposed approach for using GNNs for bacterial communities is vaguely described and not well justified. The key methods section (2.2) provides a generic description of existing GNN approaches, and is missing key microbiome specific information (in particular, what is the topology of the graph). That information is provided in Supplementary information: the graph is fully connected. This makes statements in the manuscript such as “By using k graph convolutional layers after one another we can achieve k-hop information propagation” rather misleading. \n\nOverall, the proposed method - applying GNN model in a straightforward way to a very small, fully-connected graph - is poorly justified and weak on novelty.'}

--- Unique Review 3 ---
{'rating': '3: reject, not good enough', 'confidence': '3: You are fairly confident in your assessment. It is possible that you did not understand some parts of the submission or that you are unfamiliar with some pieces of related work. Math/other details were not carefully checked.', 'summary': 'The paper tested the idea of using MPGNN or GraphSAGE to learn generalizable microbial community steady-state dynamics. The proposed models were tested on  simulated and previous publicly available microbial datasets and compared with the MLP-based implementation to show the effectiveness, with the discussions on the generalizability of GNN-based implementations.', 'strengths': 'The presented comparison results with MLP-based implementation demonstrates the potential of GNN-based implementations to model microbial community dynamics.', 'weaknesses': '1. The methodological contribution is limited as the presented work is mostly implementing GNNs for microbial steady state predictions. \n\n2. The main core of the paper is based on the assumption that if there is a steady state solution to the dynamics of bacterial species, then that steady state can be predicted using the genome data of the species in the system. This is a reasonable assumption to make. However the fact that this method works only for steady state solutions needs to be emphasized. Indeed in the GLV setting in the famous example of foxes and rabbits, there could be steady state and oscillatory solutions even though the participating genomes are foxes and rabbits in both the cases. It might also be a good idea to highlight why authors expect to find (or not) only steady state solutions in systems involving microorganisms such as bacteria. This will add more strength to the paper.\n\n3. For simulations, the GLV equations along with initial conditions and parameters $\\mu_i, K_i, a_{i,j}$ drawn from different probability density functions are used to generate data. Did all such simulations lead to steady state solutions? Were any simulations that did not lead to steady state solutions discarded? Do the authors also have any comments on the frequency of steady state solutions when random parameters are used?\n\n4. Given the GLV equations, the steady state solutions can be found by solving a system of $|S|$ linear algebraic equations:\n    \\begin{equation}\n        \\sum_{j=1}^{|S|}a_{i,j}n_j = K_i.\n    \\end{equation}\nThe steady state is entirely determined by the parameters $a_{i,j}$ and $K_i$. The authors use a vector composed of $[\\mu_i, K_i, \\nu_i^s, \\nu_i^r, random]$ (where $a_{i,j} \\approx \\nu_i^s. \\nu_j^r$) to simulate the genome data in their simulation. It would be a good idea to highlight that within the simulated genome vector only the components $[K_i, \\nu_i^s, \\nu_i^r]$ determine the steady state solution.\n\n5. The parameter $a_{i,j}$ (broken into two vectors $\\nu_i^s, \\nu_j^r$ to simulate the genome) contains information on the pairwise interaction between different species. On the other hand, the information in a genome is completely intrinsic to a particular species. The authors should square these two facts.\n\n6. A proper simulation would entail simulation of the genome data. The genome data typically do not include information on interaction between species. But for simulations, the interaction matrix was used to derive $\\nu$ vectors. The claim of interpretability seems to be questionable. \n    \n7. The authors appear to be confused on equivariance and invariance. The permutation invariance justification for using graph neural networks is confusing. For example, GLV models are widely used to model the dynamics of microorganisms. But the GLV model is not permutation invariant. The authors stated "\\textit{When shuffling the order of bacteria within the train and test communities, the accuracy of MLPs drops significantly, clearly showing that the dynamics learned by MLPs are not invariant to permutations...}" It is to be expected that shuffling the data will lead to reduction in performance of MLP based models. But as long as all the training and testing is done with a particular order of species, it should not matter.\n\n8. The authors need to provide details on how the node (genome) attributes were obtained, especially $\\nu$\'s, as in real-world data, the ground-truth interaction $a_{ij}$ is not available.'}

--- Unique Review 4 ---
{'rating': '6: marginally above the acceptance threshold', 'confidence': '3: You are fairly confident in your assessment. It is possible that you did not understand some parts of the submission or that you are unfamiliar with some pieces of related work. Math/other details were not carefully checked.', 'summary': 'The paper looks at modeling bacterial communities and their interactions using graph neural networks (GNNs). They rely on two open datasets, total n = 552 samples. The authors have downloaded genomes for the bacteria that was converted to growth encodings. To address the issue with limited data the authors also used a simulator based on the Lotka-Volterra model. They compare three different models, MLP as the standard, GNNs and MPGNN. Using GNN/MPGNN the authors were able to model but the models were sensitive to variations and generalizing to larger systems was poor. Models were better than MLP but only marginally.', 'strengths': "I found the paper interesting and I think the authors are correct that a better modeling of bacteria would open up a much better understanding of a wide range of fields. Key strengths:\n* The authors' comparative approach between models is commendable.\n* The paper addresses a clinically relevant topic, shedding light on bacterial interactions.\n* The authors' transparency regarding the challenges in scaling the mod", 'weaknesses': "While I enjoyed reading something on the outskirts of my experience, although I have grown my own tuberculosis communities in the early days of my research, I struggle with some of the basic premises:\n* Motivation & Context: The paper's motivation needs clearer alignment with real-world applications. The authors cite that understanding these communities is essential for gut, industry and space but I find the step from this paper to extrapolating to gut seems huge. The largest studied communities are 26 and this needs to be put in context with the other fields, citing Wikipedia “1010 to 1011 cells per gram of intestinal content” seems far off from the estimated single colonies. The types of bacteria should also be matched with the environment that you aim to generalize for.\n* Sample Size & DNA Inclusion: I'm concerned about the limited independent samples, especially in combination with the attempt to include DNA. Making sense of DNA has proven much more difficult than thought of in the beginning and I’m not convinced that the addition made sense. Adding it to the paper risks of overfitting the data even more. I wonder if the field wouldn’t benefit more from going from 500 samples to 1-2000 more than this paper. My experience with building models on this type of data is that they are frustratingly brittle due to the lack of data.\n* Clarity & Explanation: Coming from medicin to ML is always a challenge. It would be helpful if the paper could provide clearer explanations for terms and metrics, especially for readers transitioning from medical backgrounds. E.g. keystone bacteria are not explained, good vs acceptable R2 is unclear to the reader (I can’t even find clearly how is this calculated, despite looking in appendix A which I should not have to for the main outcome), I assume that R2 is highly dependent on the underlying complexity, also the datasets have completely different bacteria suggesting that their purpose was different but this is unclear to me despite reading it several times.\n* Simulation Impact: The paper should provide a clearer explanation of the effect of simulated colonies on the models' stability.\nRegarding the conclusion I’m a little confused as to why it doesn’t recommend including more data. I believe the authors have devoted significant time to this paper and before we put others down this path, perhaps we should wait for more data or do the authors truly feel that GEMs will be the solution?"}

In [54]:
# One row per review
df_reviews = (
    df[["paper_id", "reviews"]]
    .explode("reviews")
    .dropna(subset=["reviews"])
    .rename(columns={ "reviews": "review"})
    .copy()
)

# review number within each paper
df_reviews["review_id"] = df_reviews.groupby("paper_id").cumcount() + 1

# reorder columns
df_reviews = df_reviews[["paper_id", "review_id", "review"]]
print('==='*10)
print(df_reviews.shape)
print('==='*10)
df_reviews.head()

==============================
(38549, 3)
==============================

     paper_id  review_id                                             review
0  cXs5md5wAq          1  {'rating': '3: reject, not good enough', 'conf...
0  cXs5md5wAq          2  {'rating': '3: reject, not good enough', 'conf...
0  cXs5md5wAq          3  {'rating': '6: marginally above the acceptance...
0  cXs5md5wAq          4  {'rating': '6: marginally above the acceptance...
1  rhgIgTSSxW          1  {'rating': '8: accept, good paper', 'confidenc...

In [55]:
# One row per unique review per paper
df_reviews = (
    df[["paper_id", "reviews"]]
    .explode("reviews")
    .dropna(subset=["reviews"])
    .rename(columns={"reviews": "review"})
    .copy()
)

# convert reviews to string temporarily for duplicate detection
df_reviews["review_str"] = df_reviews["review"].astype(str)

# remove duplicate reviews within the same paper
df_reviews = df_reviews.drop_duplicates(
    subset=["paper_id", "review_str"]
)

# regenerate sequential review ids per paper
df_reviews["review_id"] = (
    df_reviews.groupby("paper_id").cumcount() + 1
)

# final columns
df_reviews = df_reviews[
    ["paper_id", "review_id", "review"]
].reset_index(drop=True)
print('==='*10)
print(df_reviews.shape)
print('==='*10)
df_reviews.head()

==============================
(38549, 3)
==============================

     paper_id  review_id                                             review
0  cXs5md5wAq          1  {'rating': '3: reject, not good enough', 'conf...
1  cXs5md5wAq          2  {'rating': '3: reject, not good enough', 'conf...
2  cXs5md5wAq          3  {'rating': '6: marginally above the acceptance...
3  cXs5md5wAq          4  {'rating': '6: marginally above the acceptance...
4  rhgIgTSSxW          1  {'rating': '8: accept, good paper', 'confidenc...

In [56]:
# Keep all original columns while creating one row per unique review

df_reviews = (
    df
    .explode("reviews")
    .dropna(subset=["reviews"])
    .rename(columns={"reviews": "review"})
    .copy()
)

# temporary string version for duplicate checking
df_reviews["review_str"] = df_reviews["review"].astype(str)

# remove duplicate reviews within the same paper
df_reviews = df_reviews.drop_duplicates(
    subset=["paper_id", "review_str"]
)

# generate sequential review ids per paper
df_reviews["review_id"] = (
    df_reviews.groupby("paper_id").cumcount() + 1
)

# remove helper column
df_reviews = df_reviews.drop(columns=["review_str"])

df_reviews.head()

,paper_id,number,title,abstract,keywords,pdf,n_reviews,review,decision,decision_comment,review_id
0,cXs5md5wAq,9504,Modelling Microbial Communities with Graph Neu...,Understanding the interactions and interplay o...,"[graph neural networks, microbial communities,...",/pdf/a4578db3b369ee02db6e42b64d333e578e1b692e.pdf,4,"{'rating': '3: reject, not good enough', 'conf...",Reject,,1
0,cXs5md5wAq,9504,Modelling Microbial Communities with Graph Neu...,Understanding the interactions and interplay o...,"[graph neural networks, microbial communities,...",/pdf/a4578db3b369ee02db6e42b64d333e578e1b692e.pdf,4,"{'rating': '3: reject, not good enough', 'conf...",Reject,,2
0,cXs5md5wAq,9504,Modelling Microbial Communities with Graph Neu...,Understanding the interactions and interplay o...,"[graph neural networks, microbial communities,...",/pdf/a4578db3b369ee02db6e42b64d333e578e1b692e.pdf,4,{'rating': '6: marginally above the acceptance...,Reject,,3
0,cXs5md5wAq,9504,Modelling Microbial Communities with Graph Neu...,Understanding the interactions and interplay o...,"[graph neural networks, microbial communities,...",/pdf/a4578db3b369ee02db6e42b64d333e578e1b692e.pdf,4,{'rating': '6: marginally above the acceptance...,Reject,,4
1,rhgIgTSSxW,9502,TabR: Tabular Deep Learning Meets Nearest Neig...,Deep learning (DL) models for tabular data pro...,"[tabular, tabular data, architecture, deep lea...",/pdf/178e173a880d7872c0a79d88e005426c20501329.pdf,4,"{'rating': '8: accept, good paper', 'confidenc...",Accept (poster),,1

In [57]:
df['decision'].value_counts()

decision
Reject                4448
Accept (poster)       1691
Accept (Poster)        869
Accept (spotlight)     347
Accept (Spotlight)     107
Accept (oral)           81
Accept (Oral)           61
Name: count, dtype: int64